# Generated by Django 6.0 on 2025-12-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_phone_no_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_no',
        ),
    ]
