# Generated by Django 6.0 on 2025-12-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
