# Generated by Django 6.0 on 2025-12-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
